### ISSUE TITLE
Crash when backup all savegames

### ISSUE THREAD

**Issue by oduverne** [BernardoGiordano/Checkpoint#99] opened 2018-06-08 06:36 UTC
Hello,

Checkpoint 3.2.0 for 3DS  crashes when I select all games and do a backup.
I starts fine but crash after some time.
It generates a super mario maker empty directory but when I backup this game individually it works fine.
I tried 3dsx and cia with the same result
I attached code dumps for the 3dsx version:
[crash_dump.zip](https://github.com/BernardoGiordano/Checkpoint/files/2083170/crash_dump.zip)

I have latest firmware with luma 9.0

* [x] Issue with Checkpoint for 3DS
* [ ] Issue with Checkpoint for Switch
* [ ] Feature request

**Comment by ddesart** [comment] 2018-06-17 15:58
Mine has been doing the same thing, but only when I have the cart inserted.  It's fine when I change saves on my digital saves.

**Comment by BernardoGiordano** [comment] 2018-07-17 19:47
can't reproduce

**Comment by oduverne** [comment] 2018-08-02 20:41
I have a hundred games installed (3dsx converted to cias) no game in the slot

**Comment by BernardoGiordano** [comment] 2018-08-03 05:18
Did you try to reproduce it on 3.4.0?

**Comment by BernardoGiordano** [comment] 2018-08-05 07:11
Closing this in 24h if I don't get any reply

**Comment by cheatfreak47** [comment] 2018-08-06 10:10
Okay, I didn't see this issue until just now, but I went ahead and tried to see if I can reproduce this, and sure enough I do crash after some time, so I can confirm this is a real issue. 

For me the only empty folder I get after running a backup operation is for Harvest Moon A New Beginning (assuming it crashed at this point?)

I also have a luma debug dump in case that's helpful.
[crash_dump_00000002.zip](https://github.com/BernardoGiordano/Checkpoint/files/2262093/crash_dump_00000002.zip)

**Comment by BernardoGiordano** [comment] 2018-08-06 10:29
@cheatfreak47 can you try to do a single backup with that title? otherwise, we'll need to setup a debugging session using GDB

**Comment by cheatfreak47** [comment] 2018-08-06 10:42
Hmm, when backing it up manually it's generating an empty folder too, so maybe that one is normally like that, I don't think I've played that game much aside from starting it up, so maybe it hasn't got any files yet.

I don't seem to notice any pattern in what file it crashes on so yeah we may need to debug it with GDB. 
I'm CheatFreak#3799 on discord so feel free to poke me on there and we'll (try to) set that up.

**Comment by cheatfreak47** [comment] 2018-08-06 12:47
Okay well this is a bit bizarre, I went ahead and build checkpoint myself to see if I could debug it with gdb and my build doesn't crash, so maybe you fixed it in a commit since the 3.4.0 stable?

**Comment by cheatfreak47** [comment] 2018-08-06 13:52
Well, it seems that the crash was indeed fixed by something you've changed since the 3.4.0 stable, I built it at the release commit and the crash is still happening.

So uh, good job fixing a bug you didn't know about! 👍

**Comment by BernardoGiordano** [comment] 2018-08-06 19:08
@oduverne @RinMaru @ddesart can you test with this build? https://www.dropbox.com/s/joowr7w45mpaelx/Checkpoint.cia?dl=0

**Closed** 2018-08-09 20:29 UTC
Labels: missing infos
