### ISSUE TITLE
does not show any save files for any of my games

### ISSUE THREAD

**Issue by 9efueifu** [BernardoGiordano/Checkpoint#89] opened 2018-05-27 14:01 UTC
Im on 5.0.2 and checkpoint is not showing any save files that i have on my switch.
i put checkpoint in the switch folder on the sd card still not showing my save files

**Comment by BernardoGiordano** [comment] 2018-05-28 09:19
can you give me a list of the games you have save files for?

**Comment by BernardoGiordano** [comment] 2018-05-29 19:43
Anyways, can't reproduce. Give me more details otherwise I'll just close the issue.

**Closed** 2018-06-07 16:38 UTC
