### ISSUE TITLE
ERROR:0000F601 Failed to commit to save device

### ISSUE THREAD

**Issue by canelodirrcto** [BernardoGiordano/Checkpoint#71] opened 2018-05-10 11:32 UTC
## Issue template

I get an error when I try to overwrite botw save ERROR:0000F601 Failed to commit to save device. I tried reinstalling everything on another sd card and still the same error, it allowed me to backup without a problem but can't write back into switch. Any ideas what it could be?

* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details
ERROR:0000F601 
Failed to commit to save device
* Entrypoint: using hbl 2.0
* System version:3.0.0
* Expected behaviour: overwrite save file
* Encountered behavior: not able to overwrite
* Result code (if available):ERROR:0000F601
* Steps to reproduce:
  * I was able to backup
  * when restoring the backup you get ERROR:0000F601 Failed to commit to save device
  * then the device freezes 
  * had to fire shut down to then restart console
### Feature request details

* I would like this feature...:
* Because...:

**Comment by BernardoGiordano** [comment] 2018-05-10 12:17
Make sure to fill all the spots inside this issue form.

**Comment by SuperOkazaki** [comment] 2018-05-10 17:18
Just would like to chime in for the same issue

* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: Hekate-ipl CFW, opening Album applet
* System version: 4.0.1
* Expected behaviour: Restoring backed up save
* Encountered behavior: Failure to restore, then system crash
* Result code (if available): ERROR:0000F601
* Steps to reproduce:
  * Back up Zelda BOTW Save File (may happen for other games too)
  * Try to restore the save file

**Comment by yellows8** [comment] 2018-05-10 18:03
"then system crash" ?

**Comment by yellows8** [comment] 2018-05-10 18:09
What's the fatal-error?

**Comment by SuperOkazaki** [comment] 2018-05-10 18:12
I don't remember off the top of my head. I can try again but I was going to stop using Hekate (even for development work) because ktemkin said that it degrades the SoC

**Comment by canelodirrcto** [comment] 2018-05-11 04:41
In my case I'm on 3.0.0 running pega switch trough the browser, I'm able to back up just fine however if you try to restore you get the above error and a few seconds later the console freezes completely forcing you to hard shutdown the switch, i also tried this with and without a cartridge on the device in case that would make a difference but still the same, also tried 2 different sd cards as well.

**Comment by yellows8** [comment] 2018-05-11 05:42
" I'm able to back up just fine however if you try to restore you get the above error and a few seconds later the console freezes completely forcing you to hard shutdown the switch"

Had this happen earlier with backup+restore for every save/user, on the last save-restore - except it hanged when pressing the 'Restore' button. Can't repro after that though...

**Comment by aznguyz** [comment] 2018-05-11 13:27
i try backup and restore right away but it still gave error

**Comment by BernardoGiordano** [comment] 2018-05-11 14:54
Reporting that I'm having error 0xF601 on 4.1.0 too, using Hekate-IPL. I'll work on the issue soon

**Comment by yellows8** [comment] 2018-05-11 15:27
@BernardoGiordano https://github.com/switchbrew/libnx/commit/02ff4915d9

**Comment by BernardoGiordano** [comment] 2018-05-11 15:58
@yellows8 still 0xF601 on 4.1.0. Also, right after restoring, console went to 2011-0301

**Comment by yellows8** [comment] 2018-05-11 16:04
:(

**Comment by yellows8** [comment] 2018-05-11 19:45
@BernardoGiordano Maybe try calling fsdevCommitDevice() at the end of io::copyFile() when writing to the save?(And keep the original call)

**Comment by BernardoGiordano** [comment] 2018-05-11 19:59
@yellows8 didn't have any issue and the save restored properly. I'm not checking for any return value inside of io::copyFile for that function though, hopefully it's not a problem. I currently have no way to do something if fsdevCommitDevice fails inside of that

**Comment by canelodirrcto** [comment] 2018-05-12 17:40
I figured that he app crashes cause it cant handle more than one save file folder at a time plus it struggles to transfer the album ad picture folder from the save files.  So you can overwrite however its gonna have to be only one save checkpoint and without picture folders, then run the overwrite and it should work

**Comment by manofsteel2017** [comment] 2018-05-13 19:29
@canelodirrcto i followered your steps and it did say success but the game won't start saying the software was closed because an error occured 
which one did you copy ? 0 or 1 ?

thanks

**Comment by canelodirrcto** [comment] 2018-05-13 21:13
I copied 0

**Comment by manofsteel2017** [comment] 2018-05-13 21:14
I got it to work.
I didn't reboot lol. 
You can't run games with homebrew enable. 

Thanks

**Comment by canelodirrcto** [comment] 2018-05-13 21:17
Yeah you always have to reboot whenever you want to run games

**Comment by BernardoGiordano** [comment] 2018-05-13 21:33
fixed in 911375a63beabbec46af4f7f03a5bcdbafa75526

**Closed by BernardoGiordano** 2018-05-13 21:33 UTC
