### ISSUE TITLE
Crash and/or hardlock when using ReiNX or SX OS

### ISSUE THREAD

**Issue by SuperOkazaki** [BernardoGiordano/Checkpoint#135] opened 2018-08-10 20:05 UTC
**This issue does exist on stable 3.4.0 but it is less reliably triggered than later**
If this is a known issue that's being worked on, then you can close this

* [ ] Issue with Checkpoint for 3DS
* [x] Issue with Checkpoint for Switch
* [ ] Feature request

### Error details

* Entrypoint: Rajikosto's AutoRCM + Fusee Launcher
* System version: 4.1.0
* Checkpoint version: release 3.4.0/compiled from commit "998be2c"
* Expected behaviour: Save backing up/restoring
* Encountered behavior: When naming a save backup, the console hardlocks and is completely unresponsive
* Result code (if available):
* Steps to reproduce:
  * Boot into ReiNX or SX OS (tested on unlicensed and licensed; same result)
  * Choose to back up a save from a game
  * Finish typing the folder name
  * When hitting "OK", the console hardlocks

**Comment by BernardoGiordano** [comment] 2018-08-16 20:27
This happens when having fs_mitm sysmodule enabled, fully disable it if you want to use Checkpoint correctly

**Comment by SuperOkazaki** [comment] 2018-08-16 23:01
Is this something that is planned on being fixed, or is it out of the hands of Checkpoint and more of an underlying issue?
I know that SX OS is a bit of a bogeyman in the Switch scene but it would be convenient for users to have support across all CFW releases.

**Comment by BernardoGiordano** [comment] 2018-08-17 04:52
It's out of hands and needs to be fixed by Atmosphere developers. fs_mitm has issues with the fs operations that Checkpoint does and throws errors like that. You need to disable if you want to properly use Checkpoint, or wait for it to be fixed but there's no ETA that I know about.

**Closed by BernardoGiordano** 2018-08-17 04:52 UTC

**Comment by SciresM** [comment] 2018-08-17 06:26
Huh. @BernardoGiordano as far as I know, fs.mitm doesn't intercept calls from homebrew. "It has issues with the fs operations Checkpoint does" can't be true, because it doesn't try to stand inbetween checkpoint and FS.

However, there is a known issue with potential handle table exhaustion in FS due to e.g. all the SD card handles CFW keeps open. I guess you could be referring to that? If so, Checkpoint could work around it by making sure it only has 1-2 handles open at any given time (I think more than 7-8 kills FS).

**Comment by BernardoGiordano** [comment] 2018-08-17 06:32
That issue has been explained vaguely to me by thirds, I reported what I heard. Anyways, yeah, the issue is the one you stated.

I can't think of situations where Checkpoint has more than 1-2 handles open at the same time, I need to trace that in some way to make sure

**Comment by SciresM** [comment] 2018-08-17 06:33
Yeah, figures. I know having like 5-10 DLCs open causes FS handle exhaustion with fsmitm atm...I think a real solution will look like domain usage (lessen used handles by fs.mitm) + increasing FS's handle table size.
